// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmeYTZVPxFNLcfPOzy7ASAPnMn3aKx2to',
    appId: '1:32975817049:web:6393c740de1b6eb80a6448',
    messagingSenderId: '32975817049',
    projectId: 'repege-project',
    authDomain: 'repege-project.firebaseapp.com',
    storageBucket: 'repege-project.appspot.com',
    measurementId: 'G-8PYMHY22R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_trwQBvtlZ4S_trlWGIDRQCpGpAlbKGA',
    appId: '1:32975817049:android:3f64b36c8d304ace0a6448',
    messagingSenderId: '32975817049',
    projectId: 'repege-project',
    storageBucket: 'repege-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_W-YM9JH_poWjj5pA2uIHzRPlhP_odc',
    appId: '1:32975817049:ios:9f1672c1630141d90a6448',
    messagingSenderId: '32975817049',
    projectId: 'repege-project',
    storageBucket: 'repege-project.appspot.com',
    iosClientId: '32975817049-tbhlj7hv44im3l06dr40naie35ua890i.apps.googleusercontent.com',
    iosBundleId: 'com.example.tcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT_W-YM9JH_poWjj5pA2uIHzRPlhP_odc',
    appId: '1:32975817049:ios:9f1672c1630141d90a6448',
    messagingSenderId: '32975817049',
    projectId: 'repege-project',
    storageBucket: 'repege-project.appspot.com',
    iosClientId: '32975817049-tbhlj7hv44im3l06dr40naie35ua890i.apps.googleusercontent.com',
    iosBundleId: 'com.example.tcc',
  );
}
